### ISSUE TITLE
[Bug]: Manifest routes only manage view component

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/application-runner#346]
### What happened?

I tried to use another component than a view. The behavior does not seems to work as the rest. 

Here is an example of failing manifest: 

```json
{
  "lenraRoutes": [{
    "path": "/",
    "view": {
      "type": "text",
      "value": "Hi"
    }
  }]
}
```

The view field should manage a view name or a component, but not just only a view component.

### Relevant log output

```Shell
lenra-app-1      | 2023/05/31 12:48:29 stdout: { context: {}, data: [], props: {}, view: null }
lenra-app-1      | 2023/05/31 12:48:29 stderr: Error: No view found for null
lenra-app-1      | 2023/05/31 12:48:29 stderr:     at getView (file:///app/node_modules/@lenra/app-server/dist/lib/indexer.js:145:15)
lenra-app-1      | 2023/05/31 12:48:29 stderr:     at Handler.handleView (file:///app/node_modules/@lenra/app-server/dist/lib/handler.js:42:26)
lenra-app-1      | 2023/05/31 12:48:29 stderr:     at Handler.handleRequest (file:///app/node_modules/@lenra/app-server/dist/lib/handler.js:31:29)
lenra-app-1      | 2023/05/31 12:48:29 stderr:     at file:///app/node_modules/@lenra/app-server/dist/lib/server.js:29:42
lenra-app-1      | 2023/05/31 12:48:29 stderr:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
lenra-app-1      | 2023/05/31 12:48:29 stderr:     at next (/app/node_modules/express/lib/router/route.js:144:13)
lenra-app-1      | 2023/05/31 12:48:29 stderr:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
lenra-app-1      | 2023/05/31 12:48:29 stderr:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
lenra-app-1      | 2023/05/31 12:48:29 stderr:     at /app/node_modules/express/lib/router/index.js:284:15
lenra-app-1      | 2023/05/31 12:48:29 stderr:     at param (/app/node_modules/express/lib/router/index.js:365:14)
```

**Comment by taorepoara** [comment]
Probably linked to https://github.com/lenra-io/lenra_cli/issues/266

**Comment by pichoemr** [comment]
The error is due to the fact that load_ui calls build_ui that call get_and_build_view only accepts view components.
We should refactor and call build_component directly in build_ui, which would allow us to manage both components and views.
In fact, get_and_build_view is ultimately called by build_component in the case of a view component, so all we need to do is remove the specific case of the first component.
